name: Docker Build

on:
  pull_request:
    paths:
      - "Dockerfile"
      - "**/*.py"
      - "requirements.txt"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t demo:${{ github.sha }} .